version: '3'
services:
  www:
    build: .
    container_name: api
    ports:
      - 8181:80
    volumes:
      - '.:/var/www/html'
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: books
  adminer:
    image: adminer
    ports:
      - 8282:8080
    restart: always
    depends_on:
      - db